### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Codemakerrr** [SCLBD/DeepfakeBench#11]
When I try to train UCF modal, it occurs to have this problem, maybe someone faces the same problem?

**Comment by YZY-stack** [comment]
I have retrained the UCF model using `ucf_detector.py` file. The training command line I used is as follow:

```
python3 train.py \
    --detector_path /home/zhiyuanyan/disfin/deepfake_benchmark/training/config/detector/ucf.yaml \
    --train_dataset "FF-F2F" "FF-DF" "FF-FS" "FF-NT" \
    --test_dataset "FaceForensics++" \
    --no-save_ckpt --no-save_feat # both save_ckpt and save_feat are False
```
  
Please note that the training data for UCF should be "FF-F2F" "FF-DF" "FF-FS" "FF-NT", not "FaceForensics++".

If you can show me more details of your implementation, I will help you fix it.
