### ISSUE TITLE
Preprocess dataset - missing .json files for datasets

### ISSUE THREAD

**Issue by vbuzovsky** [SCLBD/DeepfakeBench#116]
Since I am not able to download already preprocessed datasets linked in readme, I am trying to use the preprocess.py provied, however I cannot get the .json files that belongs to the /preprocessing/dataset_json/ directory, so I cannot run the training or testing.
Could please somebody help me, if there is anyone who used fresh datasets (FF++ mainly) and preprocessed them, or could somebody provide another link where to download the datasets? I am not able to download from the pan.baidu.com website because I cannot register with european number.
Thank you in advance

**Comment by xilulululu** [comment]
json files produced by the rearrange.py file
