### ISSUE TITLE
Why mixing DFD real into FF++ training dataset

### ISSUE THREAD

**Issue by yoctta** [SCLBD/DeepfakeBench#12]
https://github.com/SCLBD/DeepfakeBench/blob/6c6281734716b254c8d527c85d82e87c459b900f/preprocessing/rearrange.py#L164C1-L171C40

**Comment by YZY-stack** [comment]
Hi,

I understand. In the DFD (DeepfakeDetection) dataset, both fake and real videos are grouped together under the "FaceForensics++" directory. However, it doesn't mean that you will use the DFD data during training the FaceForensics++ dataset. 

The reason for putting them together is that the downloaded directory structure for the DFD dataset is organized within the "FaceForensics++" directory (after downloading from the FaceForensics++ official website), so they are managed together. However, when creating the JSON file for training, the DFD videos are separated from FaceForensics++ along with the Faceshifter videos. The resulting JSON file contains information only for the four specific methods from the DFD dataset.
