### ISSUE TITLE
Alternative datasets download option

### ISSUE THREAD

**Issue by Houssem171** [SCLBD/DeepfakeBench#132]
Hello! I am working on research regarding deepfake detection and I found your tool to be **very helpful** in my work and thank you for that! 

However, I am having issues when downloading the preprocessed data from baidu (I want to use your preprocessed data to achieve the closest results possible to your paper). Could you provide another alternative such as Google Drive? I only need the **test and validation sets** of FaceForensics++, and test set of Celeb-DFv2.

Thanks alot!

**Comment by hoangsavitar** [comment]
I have emailed and received the dataset from the author below:
Dataset: https://drive.google.com/drive/folders/1N4X3rvx9IhmkEZK-KIk4OxBrQb9BRUcs?usp=drive_link
Json: https://drive.google.com/drive/folders/1ZV3fz5MZZU5BTB5neziN6i8Yv0Z21_LO?usp=drive_link
Hope it can help you

**Comment by Houssem171** [comment]
Thank you so much!
