### ISSUE TITLE
Considering add more types of deepfake, such as audio.

### ISSUE THREAD

**Issue by Guanzhou-Ke** [SCLBD/DeepfakeBench#16]
This is really good project. Currently, the solutions of deepfake are imminent. However, methods provided by this repos are look like to address the deepfake face problem. I suggest that the maintainers could consider more about other modalities, such as audio.

Thanks a lot for this project.

**Comment by YZY-stack** [comment]
Hi,

Thank you for your kind words about our deepfake project. We truly appreciate your support and the valuable feedback you have provided.

As you correctly pointed out, our current focus primarily revolves around addressing the deepfake face forgery problem. The reason behind this choice is the significant societal impact that deepfake face manipulation can have. By prioritizing this issue, we aim to contribute to the development of robust solutions that can help combat the potential dangers posed by such manipulations.

However, we are continuously exploring ways to expand our project's scope. In our future plans, we intend to release updates that include the incorporation of diffusion-generated and GAN-generated data into our benchmark. This expansion aims to foster the development of diverse deepfake detection methods, encompassing not only facial manipulation but also more general deepfake detection.

Once again, we thank you for your valuable input. If you have any further suggestions or ideas, please don't hesitate to share them with us.

**Comment by Guanzhou-Ke** [comment]
Great, thank you for your response. I wholeheartedly agree with your decision to tackle the deep facial challenge first. I must say that both this repository and your team's work have the potential to truly inspire numerous researchers, myself included. I am determined to closely follow your progress in this field in the future, and I sincerely hope that we will have the opportunity to collaborate someday.

Keep up the good work!

**Comment by Guanzhou-Ke** [comment]
Great, thank you for your response. I wholeheartedly agree with your decision to tackle the deep facial challenge first. I must say that both this repository and your team's work have the potential to truly inspire numerous researchers, myself included. I am determined to closely follow your progress in this field in the future, and I sincerely hope that we will have the opportunity to collaborate someday.

Keep up the good work!
