### ISSUE TITLE
preprocessed the DFDC

### ISSUE THREAD

**Issue by ZZ00325** [SCLBD/DeepfakeBench#18]
Hi,

When I preprocessed the DFDC, I found that the expected data organization in the code was DFDC/train(test)/dfdc_train_part_i, but in the README, the data organization form you gave was DFDC/dfdc_train_part_i. How should I organize my data? Maybe the code is using the DFDC_test, so should I partition the DFDC data set according to the set rules so that it is consistent with the paper?

**Comment by beautyremain** [comment]
hello, I am experiencing the same problem, may I ask for your solution?
