### ISSUE TITLE
It seems like there are some bugs in the test code

### ISSUE THREAD

**Issue by fanfan1998** [SCLBD/DeepfakeBench#19]
Hello, I'm using your code and finding unexpected bugs during testing, could you please update this section of the code?
![截图 2023-08-12 20-20-33](https://github.com/SCLBD/DeepfakeBench/assets/44823699/a5affdd8-5e09-41f6-8c0c-da4f4c07345f)

**Comment by YZY-stack** [comment]
Hi, 

I have updated the YAML file of the UCF detector [ucf.yaml](https://github.com/SCLBD/DeepfakeBench/blob/main/training/config/detector/ucf.yaml)

Please try again. Thanks.
