### ISSUE TITLE
The link to Deepfake Detection Challenge (Preview) dataset seems to be out of date

### ISSUE THREAD

**Issue by QLUJiaHao** [SCLBD/DeepfakeBench#20]
<img width="396" alt="image" src="https://github.com/SCLBD/DeepfakeBench/assets/48431661/74d5d3cb-5804-46b7-912a-c165623d9d00">

Thanks for your work. However, I can't get the Deepfake Detection Challenge (Preview) dataset with your link. Could you tell me  how to get this dataset? Thanks!

**Comment by wang-qichang** [comment]
Me Too

**Comment by YZY-stack** [comment]
I will update the link very soon. Sorry for the inconvenience.
