### ISSUE TITLE
The JSON file provided in the 'DFDCP' dataset appears incomplete

### ISSUE THREAD

**Issue by fanfan1998** [SCLBD/DeepfakeBench#22]
As shown in the following figure:
![微信图片_20230816224150](https://github.com/SCLBD/DeepfakeBench/assets/44823699/1bb20cb9-a64e-447b-bddd-15d1646544d4)

**Comment by Leesoon1984** [comment]
> As shown in the following figure: ![微信图片_20230816224150](https://user-images.githubusercontent.com/44823699/261046057-1bb20cb9-a64e-447b-bddd-15d1646544d4.png)

请问解决了吗

**Comment by fanfan1998** [comment]
> > As shown in the following figure: ![微信图片_20230816224150](https://user-images.githubusercontent.com/44823699/261046057-1bb20cb9-a64e-447b-bddd-15d1646544d4.png)
> 
> 请问解决了吗

Not yet.

**Comment by YZY-stack** [comment]
Hi,

Thanks for your feedback. I'm currently engrossed in addressing a rebuttal. At the moment, I'm in the process of transferring data from my local disk to the clou d. I will update the latest version of the JSON file very soon.

**Comment by YZY-stack** [comment]
Hi, I have uploaded the DFDCP dataset with its complete JSON file. See the [Link](https://cuhko365-my.sharepoint.com/:u:/g/personal/222041040_link_cuhk_edu_cn/EazUIp_cEFFOg73BKRdO6BgBLa0u-thQEI9h_gk1GsggcA?e=7oSBTb) and the readme file for more details. Thanks!

**Comment by lulin60** [comment]
> Hi, I have uploaded the DFDCP dataset with its complete JSON file. See the [Link](https://cuhko365-my.sharepoint.com/:u:/g/personal/222041040_link_cuhk_edu_cn/EazUIp_cEFFOg73BKRdO6BgBLa0u-thQEI9h_gk1GsggcA?e=7oSBTb) and the readme file for more details. Thanks!
Can  you help me  what the password in onedrive for downloading is？could you help me ?
