### ISSUE TITLE
DFDC dataset 

### ISSUE THREAD

**Issue by lihanzhe** [SCLBD/DeepfakeBench#25]
Hello, may I ask if the test dataset for DFDC is complete? Why are there only 3725 data samples, but there are 5000 labels in the label.csv file?

**Comment by YZY-stack** [comment]
Hi. Is the DFDC or DFDCP? Which one? Can you now run the code normally?

**Comment by lihanzhe** [comment]
The test dataset for DFDC, which is the file 'test.zip'

**Comment by YZY-stack** [comment]
Hi, I have uploaded the download link of DFDC (only test data) using OneDrive. You can download it from the [Link](https://cuhko365-my.sharepoint.com/:f:/g/personal/222041040_link_cuhk_edu_cn/EjzENPTWrmxKokvW3ddTUysBJuELSKkGHvOm-zDLaPOtAA?e=awwtnp). More details can be seen in the latest readme file.
