### ISSUE TITLE
Preprocessing 

### ISSUE THREAD

**Issue by cv-chaitali** [SCLBD/DeepfakeBench#3]
Hello, I am implementing your code. The supplementary doc and the code are well organized. 
I have one doubt. So, while I was preprocessing the Celeb-DF-v2 dataset according to the instruction. YourTube Real dataset did not have any landmark or frame extraction. This issue did not happen with v1 but is happening with v2. Do I need to manually do it with the Youtube real folder. 

Thank you again for the code

**Comment by YZY-stack** [comment]
Hi,

We are very glad that our DeepfakeBench can help your work, thank you for your attention.

After reviewing your feedback and examining the provided code, it appears that there are no issues. However, it's possible that you may have missed specifying the specific dataset name in the [`config.yaml`](./preprocessing/config.yaml) file. To resolve this, please refer to the instructions in the [`README.md`](./README.md) file, as it clearly states that you need to specify the dataset name during preprocessing.

Furthermore, please note that Celeb-DF-v1 and Celeb-DF-v2 are regarded as **two different datasets** in our benchmark, and they should be processed separately. Make sure to specify the correct dataset n*ame during preprocessing to ensure accurate results.

If you have any further questions or need assistance with the code, please don't hesitate to ask.
