### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by fubenzun** [SCLBD/DeepfakeBench#30]
the nums of CDFV2 real is 890,not 590

**Comment by YZY-stack** [comment]
Hi, the result (590) is directly cited by the original Celeb-DF paper.

https://openaccess.thecvf.com/content_CVPR_2020/papers/Li_Celeb-DF_A_Large-Scale_Challenging_Dataset_for_DeepFake_Forensics_CVPR_2020_paper.pdf
