### ISSUE TITLE
bug in preprocess.py

### ISSUE THREAD

**Issue by DIY-Z** [SCLBD/DeepfakeBench#32]
https://github.com/SCLBD/DeepfakeBench/blob/1d09eb947d83666b901b3dadbb1852da0c84dcc1/preprocessing/preprocess.py#L200-L203
face_align有时会出现为None的情况，可能是因为某些情况下经过align和crop后导致检测不出人脸了，而`landmark = predictor(cropped_face, face_align[0])`会因此执行失败，触发exception。
经过测试，这里特判一下face_align是否为None可以解决这个问题（如果为None直接return）。

**Comment by YZY-stack** [comment]
感谢你的建议。我会更新到最新的版本中。
