### ISSUE TITLE
The baiduyun link of Celeb-DF-v2 is invalid

### ISSUE THREAD

**Issue by stephenivy07** [SCLBD/DeepfakeBench#33]
Hi,
Thanks for your great work! 
Could you please check the link of Celeb-DF-v2? Thank you so much!

**Comment by YZY-stack** [comment]
I will update the latest link of the dataset. Thanks for your patience.

**Comment by YZY-stack** [comment]
Hi, I have updated the download link of OneDrive for CDF-v2. Please refer to the readme file for more details.
