### ISSUE TITLE
problem in while running rearrange.py

### ISSUE THREAD

**Issue by pradeepkc11** [SCLBD/DeepfakeBench#34]
while i was running the model for CelebDF-V1,in preprocessing phase after configurating config.yaml file when i run the
rearrange.py file in terminal i am getting 
File "d:\DeepfakeBench-main\preprocessing\rearrange.py", line 263, in generate_dataset_file
    for folder in os.scandir(dataset_path):
                  ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'datasets\\Celeb-DF-v1'

this error when i go through the code i am finding unnecessary use of "frames" in 
for video_path in os.scandir(os.path.join(dataset_path, folder.name, 'frames')): this line of code and also could you specify the final dictionary file you wanted to show after running this script
Thank you in advance 
regards,
Pradeep k c

**Comment by YZY-stack** [comment]
Hi, I think you may need to generate the frames using the preprocess.py code first and then run the rearrange.py for arrangement.
