### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by sccsok** [SCLBD/DeepfakeBench#35]
Hello, @YZY-stack! The code will report `ZeroDivisionError: integer division or modulo by zero` in the test module `acc = self.correct / self.total` for each `*_detector,` when using multi-gpus training. The class variable `self.correct, self.total` for `*_detector` will be always reset as 0 for each batch-inference step. I guess the error is caused by DataParallel object duplicating a model object. This error will not occur during single-gpu training.

**Comment by WenOOI** [comment]
I have encountered the same issue.

**Comment by sccsok** [comment]
@WenOOI I solved this problem by defining a new class, while replacing the method  `get_test_metrics` in the original `trainer`.
``` 
class TestMetrics:
      def __init__(self) -> None:
          self.prob, self.label = [], []
          self.correct, self.total = 0, 0

      def get_test_metrics(self):
          y_pred = np.concatenate(self.prob)
          y_true = np.concatenate(self.label)
          # auc
          fpr, tpr, thresholds = metrics.roc_curve(y_true, y_pred, pos_label=1)
          auc = metrics.auc(fpr, tpr)
          # eer
          fnr = 1 - tpr
          eer = fpr[np.nanargmin(np.absolute((fnr - fpr)))]
          # ap
          ap = metrics.average_precision_score(y_true,y_pred)
          # acc
          acc = self.correct / self.total
          # reset the prob and label
          self.prob, self.label = [], []
          return {'acc':acc, 'auc':auc, 'eer':eer, 'ap':ap, 'pred':y_pred, 'label':y_true}

      def add_(self, pred_dict, data_dict):
          self.prob.append(
                  pred_dict['prob']
                  .detach()
                  .squeeze()
                  .cpu()
                  .numpy()
              )
          self.label.append(
                  data_dict['label']
                  .detach()
                  .squeeze()
                  .cpu()
                  .numpy()
              )
          # deal with acc
          _, prediction_class = torch.max(pred_dict['cls'], 1)
          correct = (prediction_class == data_dict['label']).sum().item()
          self.correct += correct
          self.total += data_dict['label'].size(0)
```

**Comment by WenOOI** [comment]
@sccsok Thanks a lot! This will be very helpful.

Moreover, I came across some other issues while working on this project. Would you be willing to discuss them with me?

When I try to use the saved checkpoint with 'torch.load()' for testing, I'm unable to achieve the same results as during training. Have you experienced this issue before?

[https://github.com/SCLBD/DeepfakeBench/issues/36#issue-1989212563](my issues is here)

**Comment by sccsok** [comment]
@WenOOI The different results for training and testing processes are caused by different datasets used in `train.py` and `test.py`. In `train.py` , the testing process uses the same transforms as the training process, while it does not use any transforms in `test.py`.

**Comment by WenOOI** [comment]
I am very grateful for your patient answer. But it may not be due to this reason, as I already modified this part of the code.
`        
        # Do transforms
        if self.mode == 'train' and self.config['use_data_augmentation']:
            image_trans, landmarks_trans, mask_trans = self.data_aug(image, landmarks, mask)
        else:
            image_trans, landmarks_trans, mask_trans = deepcopy(image), deepcopy(landmarks), deepcopy(mask)
`
I have added a condition to determine whether it is in a training state. But it doesn't work. 

I have been confused for a long time. Thank you again for your help! I'll try to find out the reason later.

**Comment by sccsok** [comment]
@WenOOI The other reason for your problem may be the misuse of class/global  variables. If you adjust the following code, you should reset the `self.prob, self.label = [], []; self.correct, self.total = 0, 0` , or define a new `TestMetrics `object for **each dataset in each epoch**.


> @WenOOI I solved this problem by defining a new class, while replacing the method `get_test_metrics` in the original `trainer`.
> 
> ```
> class TestMetrics:
>       def __init__(self) -> None:
>           self.prob, self.label = [], []
>           self.correct, self.total = 0, 0
> 
>       def get_test_metrics(self):
>           y_pred = np.concatenate(self.prob)
>           y_true = np.concatenate(self.label)
>           # auc
>           fpr, tpr, thresholds = metrics.roc_curve(y_true, y_pred, pos_label=1)
>           auc = metrics.auc(fpr, tpr)
>           # eer
>           fnr = 1 - tpr
>           eer = fpr[np.nanargmin(np.absolute((fnr - fpr)))]
>           # ap
>           ap = metrics.average_precision_score(y_true,y_pred)
>           # acc
>           acc = self.correct / self.total
>           # reset the prob and label
>           self.prob, self.label = [], []
>           return {'acc':acc, 'auc':auc, 'eer':eer, 'ap':ap, 'pred':y_pred, 'label':y_true}
> 
>       def add_(self, pred_dict, data_dict):
>           self.prob.append(
>                   pred_dict['prob']
>                   .detach()
>                   .squeeze()
>                   .cpu()
>                   .numpy()
>               )
>           self.label.append(
>                   data_dict['label']
>                   .detach()
>                   .squeeze()
>                   .cpu()
>                   .numpy()
>               )
>           # deal with acc
>           _, prediction_class = torch.max(pred_dict['cls'], 1)
>           correct = (prediction_class == data_dict['label']).sum().item()
>           self.correct += correct
>           self.total += data_dict['label'].size(0)
> ```

**Comment by YZY-stack** [comment]
Hello, I am grateful for your code, which appears to function effectively in a DDP setup with multi-GPU training. However, as I currently have access to only one GPU, I haven't had the opportunity to implement the multi-GPU training myself.

**Comment by WenOOI** [comment]
@sccsok 


> @WenOOI The different results for training and testing processes are caused by different datasets used in `train.py` and `test.py`. In `train.py` , the testing process uses the same transforms as the training process, while it does not use any transforms in `test.py`.


I'm very grateful for your help. This fixed my problems. Actually, another reason is caused by my careless mistake.

Thanks a lot!
