### ISSUE TITLE
preprocess slow when using ProcessPoolExecutor

### ISSUE THREAD

**Issue by DIY-Z** [SCLBD/DeepfakeBench#37]
In the concurrent.futures module, there are two classes, **`ThreadPoolExecutor`** and **`ProcessPoolExecutor`**. 
For IO-intensive tasks, it is recommended to use multithreading (ThreadPoolExecutor), while for compute-intensive tasks, multiprocessing (ProcessPoolExecutor) is preferred. 
_Since the primary task of preprocess.py is to extract faces and save face images_, it falls under the category of **IO-intensive tasks**. 
Therefore, it is advisable to replace ProcessPoolExecutor with ThreadPoolExecutor in the code. 
I found that using `ThreadPoolExecutor` is indeed faster than ProcessPoolExecutor.

https://github.com/SCLBD/DeepfakeBench/blob/6bc3ea01cdc768b17bd37b5e0eca85ecdfb10472/preprocessing/preprocess.py#L380-L381

**Comment by YZY-stack** [comment]
Hi,

Your suggestion was indeed correct. I have changed the `ProcessPool` into `ThreadPool` and have pushed them to the latest branch.

I greatly appreciate your valuable contribution.

Thank you.
