### ISSUE TITLE
There is a bug in the calculation of accuracy (ACC) for UCF

### ISSUE THREAD

**Issue by beautyremain** [SCLBD/DeepfakeBench#38]
I notice that the labels of FF-F2F, FF-FS, and FF-NT are set to 1,2,3, respectively. I know it is designed for the training of specific forgery features. However, the implementation for ACC calculation is disrupted, that is, in ucf_detector.py:
<img width="1197" alt="企业微信截图_17011691041637" src="https://github.com/SCLBD/DeepfakeBench/assets/48754653/f650995d-8fa0-4872-ae4f-88745fb30519">
It can be observed that the predicted_class is  1 or 0, while labels are 0,1,2,3 according to the deepfake methods. Here is my modification:
<img width="516" alt="企业微信截图_17011695769204" src="https://github.com/SCLBD/DeepfakeBench/assets/48754653/07d4f2fe-f0a2-48c4-9a83-e80803d432a3">
Then it should work well.

**Comment by YZY-stack** [comment]
Hi, 

Thank you for your diligence in pointing out an oversight in the code. I've made the necessary modifications to the code and pushed it to the latest branch.

Thank you once again for your valuable contribution.
