### ISSUE TITLE
There appears to be a discrepancy between the reproduced results and the paper results

### ISSUE THREAD

**Issue by gbljdgb** [SCLBD/DeepfakeBench#48]
Hello author, I tried to reproduce the results of your experiment, I placed the ucf_best.pth you provided with the training/weights folder, and after that I ran it on FF++ , DFDC (downloaded processed version), DFD and Celeb-DF v2 (downloaded processed version). The results of the tests, which are as follows, do not seem to be comparable to the results of the paper.

Here are the results for FF++, which turned out very well
<img width="552" alt="image" src="https://github.com/SCLBD/DeepfakeBench/assets/88969496/2c33eaba-07ee-463d-b9d1-b81e9ce481ba">

Here are the results for the other datasets, which are about 5-12 points lower than the paper's results.
<img width="552" alt="image" src="https://github.com/SCLBD/DeepfakeBench/assets/88969496/3cd50f78-4190-4229-a733-f9b64e86cb21">
<img width="556" alt="image" src="https://github.com/SCLBD/DeepfakeBench/assets/88969496/6c4f35c1-8de5-4e8e-b8b7-93b16a5a5c27">

Could you give me possible reasons for this?

Thanks.

**Comment by Blosslzy** [comment]
I got the same results as yours. Have you solved this issue?
