### ISSUE TITLE
ValueError: dataset FaceForensics++ not exist!

### ISSUE THREAD

**Issue by Sun-researcher** [SCLBD/DeepfakeBench#52]
This problem occurred when I was running programs in windows. When I enter the python training/train. py -- detector_path. / training/config/detector/xception yaml instructions.
![屏幕截图 2024-03-26 102545](https://github.com/SCLBD/DeepfakeBench/assets/84301317/41a4f3aa-ca16-4f30-852b-2dbfddb4161c)
![屏幕截图 2024-03-26 102616](https://github.com/SCLBD/DeepfakeBench/assets/84301317/d7d55606-aab2-4a1b-8f2c-d9553e210e74)
![屏幕截图 2024-03-26 102715](https://github.com/SCLBD/DeepfakeBench/assets/84301317/719a966e-94f1-44e1-a664-264df6c8db65)
![屏幕截图 2024-03-26 102758](https://github.com/SCLBD/DeepfakeBench/assets/84301317/81f462f6-0443-4237-9028-e6749c133193)

**Comment by 010108** [comment]
Hello! I'm also having the same problem, how can I solve it?
