### ISSUE TITLE
What if I want to train my own network model

### ISSUE THREAD

**Issue by Sun-researcher** [SCLBD/DeepfakeBench#53]
I want to train my own model with your framework, how can I modify it.

**Comment by Sun-researcher** [comment]
![屏幕截图 2024-03-26 195614](https://github.com/SCLBD/DeepfakeBench/assets/84301317/ecf35c4a-5b12-4dca-bb24-c45de48e5791)

**Comment by YZY-stack** [comment]
I apologize for the delayed response. Regarding the "xxx_detector.py" file within the ./training/detectors folder (which can be a new detection method), its purpose is to implement the feature extraction, classifier, initialization function, and other necessary functions. The logic for implementing these functions is as follows:

1. First, load the train/test data using the dataloader provided in the trainer/trainer.py file.
The trainer will then pass the data dictionary (data_dict) into the detector (xxx_detector.py). Consequently, you can access the data_dict in the "forward" function of the detector file (xxx_detector.py).
2. Next, implement the "feature" function to take the data_dict as input and output a feature vector or feature map. The output of the feature function will be passed through the "classifier" function to obtain the final output (e.g., binary classification result).
3. Add your new detector in the "training/detector/__init__.py" file.

Please try implementing a new detector based on the information provided above. If you have any further questions or require clarification, do not hesitate to reach out to me.
