### ISSUE TITLE
KeyError : 'conv 1. weight

### ISSUE THREAD

**Issue by hugplz** [SCLBD/DeepfakeBench#56]
Traceback (most recent cal1 last):
Fi1e "training/test.py", line 187,in <module>
main(
Fi1e "training/test.py", 1ine 169,in mainmodel = model_class(config).to(device)
File "/root/ autod1-tmp/DeepfakeBench-main/training/detectors/spsl_detector.py", line 61, in _init_self.backbone = self.bui1d_backbone(config)
Fi1e " /root/autodl-tmp/DeepfakeBench-main/training/detectors/spsl_detector.py"，1ine 80，in build_backbon
conv 1_data = state_dict.pop (' conv 1. weight')
KeyError : 'conv 1. weight'

the problem seems only happen in f detector
naive and s detector is ok

**Comment by Shirley0302** [comment]
打印state_dict加载的模型会发现名称不对
conv 1_data = state_dict.pop (' conv 1. weight')
改成 conv 1_data = state_dict.pop (' backbone.conv 1. weight')
