### ISSUE TITLE
FF++ dataset 

### ISSUE THREAD

**Issue by MetroTY** [SCLBD/DeepfakeBench#64]
Hi author, is positive and negative sample imbalance considered for FF++ dataset? I read some papers where the positive samples are quadruple sampled to equalize with the negative samples.

**Comment by YZY-stack** [comment]
Yes. You can use "FF-DF, FF-F2F, FF-FS, FF-NT" to replace the original "FaceForensics++" in the training phase. This would lead to quadruple sampling as you mention.

For instance:

python3 train.py --train_dataset FF-DF, FF-F2F, FF-FS, FF-NT --test_dataset Celeb-DF-v1
