### ISSUE TITLE
Error occurred in SBI

### ISSUE THREAD

**Issue by thought-yyds** [SCLBD/DeepfakeBench#68]
too many indices for array: array is 2-dimensional, but 3 were indexed
TypeError: pic should be PIL Image or ndarray. Got <class 'NoneType'>

**Comment by thought-yyds** [comment]
mask = random_get_hull(landmark, img, hull_type)[:,:,0]-->mask = random_get_hull(landmark, img, hull_type)

**Comment by ZZ00325** [comment]
Hello, How do you slove the problem?

**Comment by thought-yyds** [comment]
> Hello, How do you slove the problem?

In sbi_api lines for 238&268: mask = random_get_hull(landmark, img, hull_type)[:,:,0]-->mask = random_get_hull(landmark, img, hull_type)
you can try

**Comment by ZZ00325** [comment]
Hello, follow your setting, i got the Error: ValueError: y should be a 1d array, got an array of shape (48, 3) instead.

**Comment by ZZ00325** [comment]
Hello, i fix the bug, but when the demo run until epoch3, i got a new Error: OSError: [Errno 12] Cannot allocate memory. 
This may be Memory Leak？ Could you tell me how to slove? Thank you! @thought-yyds

**Comment by ZZ00325** [comment]
Hello, could you give me your fix code of sbi? @thought-yyds

**Comment by thought-yyds** [comment]
I didn't report your memory error when I ran the program, you can try to make your epoch smaller, I didn't change the other parts of the code

**Comment by ZZ00325** [comment]
Thanks for your answer. 
Could you tell me what do you got the best AUC of FF++ with the code of sbi?
And other dateset? @thought-yyds
