### ISSUE TITLE
复现结果

### ISSUE THREAD

**Issue by Leesoon1984** [SCLBD/DeepfakeBench#7]
复现结果与表二有较大的差异，有人复现了吗？

**Comment by YZY-stack** [comment]
您好，

我们所有的实验结果都在readme.md中提供，您可以使用这些结果进行进一步的分析。对于结果的复现，需要确保实验的所有settings和论文以及supplementary中一致，这样才能保证结果的可复现。

感谢您的关注。

**Comment by QLUJiaHao** [comment]
> 复现结果与表二有较大的差异，有人复现了吗？

我对EfficientNetb4和Xception使用DeepfakeBench进行了复现，所得到的结果均比论文表二中的数据高出几个点，请问您是否也得到类似的结果了？
