### ISSUE TITLE
shuffle_dataset 

### ISSUE THREAD

**Issue by emanalattas** [SCLBD/DeepfakeBench#70]
Hello..
I tried to run the evaluation, but I got this error:
from .shuffle_dataset import ShuffleDataset
ModuleNotFoundError: No module named 'training.dataset.shuffle_dataset'

Where can I get this file?

Thanks.

**Comment by emanalattas** [comment]
Also, I couldn't find this file:
from .yzy_dataset import YZYDataset

Any help in this issue?

Thanks

**Comment by hejian-pc** [comment]
I had this problem too, have you solved it yet?

**Comment by YZY-stack** [comment]
I have fixed this issue. Check the lastest version please!
