### ISSUE TITLE
Please consider placing data on other file sharing platform

### ISSUE THREAD

**Issue by pakio** [SCLBD/DeepfakeBench#8]
Thanks for the great benchmark!
I really appreciate the project and how you prepared all the detailed instruction.

One small request about the service where the datasets located,  could you consider putting the data outside Baidu?
I personally have concern about security using Baidu and don't want to install the Baidu file client, but they doesn't allow us to download the file without the client.
And also, because the server is not available in each country, like the most of the others does, the latency is super slow.

It would be appreciated if you could kindly consider storing the data in other file sharing service, Google Drive for example.

**Comment by YZY-stack** [comment]
Thank you for your valuable suggestions, we will also provide the download link of the google drive later :)

**Comment by YZY-stack** [comment]
@pakio Hi, I have updated the download link using **OneDrive**. You can download the data including videos, frames, masks, and landmarks from the download link I provided. Please refer to the readme file for more details.

**Comment by YZY-stack** [comment]
@pakio Also, thanks for your patience and suggestion :)

**Comment by pakio** [comment]
hi @YZY-stack, sorry for the late response. I just noticed your replay, really appreciate your work migrating the data to OneDrive! Your work is really amazing and will definitely try them out soon once I got my time available.
