### ISSUE TITLE
KeyError: 'label_dict' in test.py

### ISSUE THREAD

**Issue by Jin1024520** [SCLBD/DeepfakeBench#81]
This is somewhat similar to the other problem, and my solution was to put the dict from the train into the test.I don't know if that's right.

**Comment by bendoesai** [comment]
I did this as well. It seems to work fine. all the label_dict does is map the images to their respective labels (0 or 1)

**Comment by YZY-stack** [comment]
Hi. The solution (put the dict from the train into the test) is definitely correct! I have fixed this bug in the latest version.
