### ISSUE TITLE
The results are much worse than in the paper.

### ISSUE THREAD

**Issue by githuboflk** [SCLBD/DeepfakeBench#85]
I am reproducing your UCF, following exactly the setup and data processing steps you gave. But the results are much worse than in the paper.

![Snipaste_2024-06-25_08-14-46](https://github.com/SCLBD/DeepfakeBench/assets/46597718/3039a802-6bdc-4770-bdb0-01b6b0a22e42)

**Comment by githuboflk** [comment]
![CDFv2](https://github.com/SCLBD/DeepfakeBench/assets/46597718/94be94d1-3842-4743-b42e-b99756f73a30)

**Comment by deruyter92** [comment]
I have the same problem. Exactly followed the instructions

**Comment by YZY-stack** [comment]
Hi, thanks for your interest. In the benchmark, we use **unified** training settings, data, and hyperparameters. In UCF, we set and tune **customized** parameters for the model. In addition, more **randomization** is added to the data preprocessing and training process to increase the diversity of the data.

**Comment by githuboflk** [comment]
@YZY-stack Thank you for your reply. I wonder if you can share the unique Settings of UCF? I checked the issue list and no one seems to be able to reproduce your results.
