### ISSUE TITLE
altfreezing_detector的build_backbone和classifier未实现

### ISSUE THREAD

**Issue by Ftgn-dpA** [SCLBD/DeepfakeBench#95]
不知道是不是这个原因导致训练altfreezing时acc极低，auc、err和ap都无法计算

**Comment by Leesoon1984** [comment]
> 不知道是不是这个原因导致训练altfreezing时acc极低，auc、err和ap都无法计算

AltFreezing 应该也没有实现吧，现在的版本就是就是ResNet50-3D？
