### ISSUE TITLE
I meet the questions when I run the example train.py

### ISSUE THREAD

**Issue by J-T-kullo** [SCLBD/DeepfakeBench#99]
Traceback (most recent call last):
  File "training/train.py", line 324, in <module>
    main()
  File "training/train.py", line 249, in main
    task_str = f"_{config['task_target']}" if config['task_target'] is not None else ""
KeyError: 'task_target'

**Comment by Jin1024520** [comment]
I also encountered this problem, my solution is to determine whether the task_target exists in the config, if it does, execute the original code, if not, set it to ""

**Comment by IIyaJ** [comment]
> I also encountered this problem, my solution is to determine whether the task_target exists in the config, if it does, execute the original code, if not, set it to ""
I also encountered the same problem. How did you modify the program code specifically? Look forward to your reply!
